name: planetary-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - bottleneck>=1.5.0
  - dask
  - dask-ml
  - distributed
  - gdal
  - netcdf4>=1.7.2
  - pyproj
  - pydap=3.2.2       # Last version that supports Python 3.9
  - packaging<21
  - setuptools<58
  - xarray<=2023.12.0 # Last version that supports Python 3.9
  - pip
  - pip:
      - copernicusmarine>=2.0.1
      - odc-stac
      - planetary-computer
      - pystac-client
