services:
  jupyterhub:
    build: jupyterhub
    container_name: jupyterhub
    ports:
      - "8000:8000"
    volumes:
      - ./jupyterhub:/srv/jupyterhub
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/group:/etc/group:ro
      - /var/run/docker.sock:/var/run/docker.sock  # so jupyterhub can spawn a docker container
    networks:
      - imars-jupyterhub_default  # Must match the network name

networks:
  imars-jupyterhub_default:
    external: true
    




#    environment:
#      - DOCKER_NOTEBOOK_IMAGE=quay.io/jupyter/scipy-notebook
#      - JUPYTERHUB_ADMIN=adminusername
#    command: >
#      jupyterhub
#      --Spawner.cmd="start-singleuser.sh"
