name: planetary-env
channels:
  - conda-forge
  - defaults
dependencies:
  - bottleneck>=1.5.0
  - dask
  - dask-ml
  - distributed
  - gdal
  - netcdf4>=1.7.2
  - numpy
  - pandas
  - pydap>=3.5.5
  - pyproj
  - python=3.11
  - xarray>=2025.3.0
  - pip
  - pip:
      - copernicusmarine>=2.0.1
      - odc-stac
      - planetary-computer
      - pystac-client